on:
  reddit:
    url: https://www.reddit.com/r/all/top/.json?t=week
    source: json
    config:
      active: false
      # limit: 2
      every: "33 8 * * *"
      outputsMode: combine
      exportOutputs: true
      format: |
        delete item.all_awardings
        item.original_created_utc = item.created_utc;
        item.created_utc = Math.floor(Date.now() / 1000);
        return item
      filterScript: |
        if(item.score>130000){
          return true
        }
    requestConfig:
      params:
        raw_json: 1
jobs:
  savereddittopissues:
    name: save to json
    runs-on: ubuntu-latest
    steps:
      - name: Format reddit JSON
        env:
          OUTPUTS_PATH: ${{ on.reddit.outputs.path }}
        uses: ./.github/actions/format
        with:
          function: reddit
      - name: Create Reddit JSON
        uses: actions/github-script@v3
        env:
          OUTPUTS_PATH: ${{ on.reddit.outputs.path }}
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const generateSources = require(`${process.env.GITHUB_WORKSPACE}/scripts/generate-reddit-top-weekly-module.js`)
            await generateSources()
            return true
