name: Build get Metadata
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "scripts/src/get-metadata.js"
jobs:
  run:
    runs-on: ubuntu-20.04
    name: Run
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: npm install && npm run build:meta
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: scripts/get-metadata
