name: Build Change My View Site
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "content/**"
  #     - "i18n/i18next/zh/**"
  #     - "i18n/post-resource/zh/reddit_--_reddit-changemyview*.json"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/cmv
          event-type: redeploy
