name: Build translate
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/actions/translate/src/**"
jobs:
  run:
    runs-on: macos-latest
    name: Run
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - run: npm install && npm run build:action
        env:
          CI: true
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            .github/actions/translate/dist
            .github/actions/translate/local-chromium
